// Code generated by protoc-gen-go. DO NOT EDIT.
// source: celestial.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	celestial.proto

It has these top-level messages:
	KV
	NodeData
	ListReq
	Payload
	Content
	MutateReq
	ListResp
	MutateResp
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enumerations
type ReqKind int32

const (
	ReqKind_SECRETS    ReqKind = 0
	ReqKind_CONFIGS    ReqKind = 1
	ReqKind_ACTIONS    ReqKind = 2
	ReqKind_NAMESPACES ReqKind = 3
)

var ReqKind_name = map[int32]string{
	0: "SECRETS",
	1: "CONFIGS",
	2: "ACTIONS",
	3: "NAMESPACES",
}
var ReqKind_value = map[string]int32{
	"SECRETS":    0,
	"CONFIGS":    1,
	"ACTIONS":    2,
	"NAMESPACES": 3,
}

func (x ReqKind) String() string {
	return proto.EnumName(ReqKind_name, int32(x))
}
func (ReqKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Other messages
type KV struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type NodeData struct {
	NodeId string `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	Data   []*KV  `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *NodeData) Reset()                    { *m = NodeData{} }
func (m *NodeData) String() string            { return proto.CompactTextString(m) }
func (*NodeData) ProtoMessage()               {}
func (*NodeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NodeData) GetData() []*KV {
	if m != nil {
		return m.Data
	}
	return nil
}

// Requests
type ListReq struct {
	Compare string  `protobuf:"bytes,1,opt,name=compare" json:"compare,omitempty"`
	Labels  []*KV   `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty"`
	Kind    ReqKind `protobuf:"varint,3,opt,name=kind,enum=service.ReqKind" json:"kind,omitempty"`
	Extras  []*KV   `protobuf:"bytes,4,rep,name=extras" json:"extras,omitempty"`
}

func (m *ListReq) Reset()                    { *m = ListReq{} }
func (m *ListReq) String() string            { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()               {}
func (*ListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListReq) GetCompare() string {
	if m != nil {
		return m.Compare
	}
	return ""
}

func (m *ListReq) GetLabels() []*KV {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ListReq) GetKind() ReqKind {
	if m != nil {
		return m.Kind
	}
	return ReqKind_SECRETS
}

func (m *ListReq) GetExtras() []*KV {
	if m != nil {
		return m.Extras
	}
	return nil
}

type Payload struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Params []string `protobuf:"bytes,2,rep,name=params" json:"params,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Payload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Payload) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Content struct {
	Region   string     `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	Clusters []string   `protobuf:"bytes,2,rep,name=clusters" json:"clusters,omitempty"`
	Labels   []*KV      `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty"`
	Data     []*Payload `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Content) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Content) GetClusters() []string {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *Content) GetLabels() []*KV {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Content) GetData() []*Payload {
	if m != nil {
		return m.Data
	}
	return nil
}

type MutateReq struct {
	Content []*Content `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
	Kind    ReqKind    `protobuf:"varint,2,opt,name=kind,enum=service.ReqKind" json:"kind,omitempty"`
}

func (m *MutateReq) Reset()                    { *m = MutateReq{} }
func (m *MutateReq) String() string            { return proto.CompactTextString(m) }
func (*MutateReq) ProtoMessage()               {}
func (*MutateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MutateReq) GetContent() []*Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MutateReq) GetKind() ReqKind {
	if m != nil {
		return m.Kind
	}
	return ReqKind_SECRETS
}

// Replys
type ListResp struct {
	Error string      `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Data  []*NodeData `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *ListResp) Reset()                    { *m = ListResp{} }
func (m *ListResp) String() string            { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()               {}
func (*ListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResp) GetData() []*NodeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type MutateResp struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *MutateResp) Reset()                    { *m = MutateResp{} }
func (m *MutateResp) String() string            { return proto.CompactTextString(m) }
func (*MutateResp) ProtoMessage()               {}
func (*MutateResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MutateResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*KV)(nil), "service.KV")
	proto.RegisterType((*NodeData)(nil), "service.NodeData")
	proto.RegisterType((*ListReq)(nil), "service.ListReq")
	proto.RegisterType((*Payload)(nil), "service.Payload")
	proto.RegisterType((*Content)(nil), "service.Content")
	proto.RegisterType((*MutateReq)(nil), "service.MutateReq")
	proto.RegisterType((*ListResp)(nil), "service.ListResp")
	proto.RegisterType((*MutateResp)(nil), "service.MutateResp")
	proto.RegisterEnum("service.ReqKind", ReqKind_name, ReqKind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CelestialService service

type CelestialServiceClient interface {
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	Mutate(ctx context.Context, in *MutateReq, opts ...grpc.CallOption) (*MutateResp, error)
}

type celestialServiceClient struct {
	cc *grpc.ClientConn
}

func NewCelestialServiceClient(cc *grpc.ClientConn) CelestialServiceClient {
	return &celestialServiceClient{cc}
}

func (c *celestialServiceClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := grpc.Invoke(ctx, "/service.CelestialService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *celestialServiceClient) Mutate(ctx context.Context, in *MutateReq, opts ...grpc.CallOption) (*MutateResp, error) {
	out := new(MutateResp)
	err := grpc.Invoke(ctx, "/service.CelestialService/Mutate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CelestialService service

type CelestialServiceServer interface {
	List(context.Context, *ListReq) (*ListResp, error)
	Mutate(context.Context, *MutateReq) (*MutateResp, error)
}

func RegisterCelestialServiceServer(s *grpc.Server, srv CelestialServiceServer) {
	s.RegisterService(&_CelestialService_serviceDesc, srv)
}

func _CelestialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelestialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CelestialService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelestialServiceServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CelestialService_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelestialServiceServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CelestialService/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelestialServiceServer).Mutate(ctx, req.(*MutateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CelestialService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.CelestialService",
	HandlerType: (*CelestialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CelestialService_List_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _CelestialService_Mutate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestial.proto",
}

func init() { proto.RegisterFile("celestial.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x3f, 0x88, 0x93, 0x89, 0x54, 0xdc, 0x01, 0x21, 0x2b, 0x17, 0x22, 0x03, 0x52, 0x54,
	0x41, 0x0e, 0xa9, 0xb8, 0x13, 0x99, 0x50, 0x45, 0xa1, 0x69, 0x65, 0x57, 0xbd, 0x71, 0xd8, 0xc6,
	0x23, 0x64, 0xd5, 0xf1, 0xba, 0xeb, 0x4d, 0x44, 0xff, 0x01, 0x77, 0xfe, 0x30, 0x5a, 0xef, 0xae,
	0x0b, 0xa5, 0xf4, 0xe6, 0xb7, 0x33, 0xf3, 0xf6, 0xbd, 0xb7, 0x63, 0x78, 0xbe, 0xa1, 0x92, 0x1a,
	0x59, 0xb0, 0x72, 0x5a, 0x0b, 0x2e, 0x39, 0x06, 0x0d, 0x89, 0x7d, 0xb1, 0xa1, 0xf8, 0x3d, 0xb8,
	0xab, 0x2b, 0x0c, 0xc1, 0xbb, 0xa1, 0xbb, 0xc8, 0x19, 0x3b, 0x93, 0x41, 0xaa, 0x3e, 0xf1, 0x25,
	0x3c, 0xdb, 0xb3, 0x72, 0x47, 0x91, 0xdb, 0x9e, 0x69, 0x10, 0x27, 0xd0, 0x5f, 0xf3, 0x9c, 0x3e,
	0x33, 0xc9, 0xf0, 0x15, 0xf4, 0x2a, 0x9e, 0xd3, 0x32, 0x37, 0x63, 0x06, 0xe1, 0x6b, 0xf0, 0x73,
	0x26, 0x59, 0xe4, 0x8e, 0xbd, 0xc9, 0x70, 0x36, 0x9c, 0x9a, 0x9b, 0xa6, 0xab, 0xab, 0xb4, 0x2d,
	0xc4, 0xbf, 0x1c, 0x08, 0xbe, 0x16, 0x8d, 0x4c, 0xe9, 0x16, 0x23, 0x08, 0x36, 0x7c, 0x5b, 0x33,
	0x41, 0x86, 0xc5, 0x42, 0x7c, 0x03, 0xbd, 0x92, 0x5d, 0x53, 0xd9, 0x3c, 0x46, 0x64, 0x4a, 0xf8,
	0x16, 0xfc, 0x9b, 0xa2, 0xca, 0x23, 0x6f, 0xec, 0x4c, 0x0e, 0x67, 0x61, 0xd7, 0x92, 0xd2, 0xed,
	0xaa, 0xa8, 0xf2, 0xb4, 0xad, 0x2a, 0x2a, 0xfa, 0x21, 0x05, 0x6b, 0x22, 0xff, 0x11, 0x2a, 0x5d,
	0x8a, 0x3f, 0x42, 0x70, 0xc1, 0xee, 0x4a, 0xce, 0x72, 0x44, 0xf0, 0x2b, 0xb6, 0xb5, 0x8a, 0xda,
	0x6f, 0xe5, 0xb6, 0x66, 0x82, 0x6d, 0xb5, 0x9c, 0x41, 0x6a, 0x50, 0xfc, 0xd3, 0x81, 0x20, 0xe1,
	0x95, 0xa4, 0x4a, 0xaa, 0x1e, 0x41, 0xdf, 0x0b, 0x5e, 0xd9, 0x44, 0x34, 0xc2, 0x11, 0xf4, 0x37,
	0xe5, 0xae, 0x91, 0x24, 0xec, 0x74, 0x87, 0xff, 0xb0, 0xe9, 0x3d, 0x69, 0xb3, 0x8d, 0x54, 0xcb,
	0xbf, 0xb7, 0x69, 0x04, 0x9b, 0x5c, 0xbf, 0xc1, 0xe0, 0x6c, 0x27, 0x99, 0x24, 0x15, 0xec, 0xb1,
	0x0a, 0xb6, 0x95, 0x15, 0x39, 0x0f, 0xa6, 0x8c, 0xdc, 0xd4, 0x36, 0x74, 0x29, 0xba, 0x4f, 0xa5,
	0x18, 0x9f, 0x42, 0x5f, 0xbf, 0x5a, 0x53, 0xab, 0xed, 0x20, 0x21, 0xb8, 0x30, 0x46, 0x35, 0xc0,
	0x77, 0x7f, 0xbd, 0xfc, 0x51, 0xc7, 0x63, 0x57, 0xc6, 0xe8, 0x8c, 0x01, 0xac, 0xce, 0xff, 0x51,
	0x1d, 0x7f, 0x82, 0xc0, 0xdc, 0x8e, 0x43, 0x08, 0xb2, 0x45, 0x92, 0x2e, 0x2e, 0xb3, 0xf0, 0x40,
	0x81, 0xe4, 0x7c, 0xfd, 0x65, 0x79, 0x9a, 0x85, 0x8e, 0x02, 0xf3, 0xe4, 0x72, 0x79, 0xbe, 0xce,
	0x42, 0x17, 0x0f, 0x01, 0xd6, 0xf3, 0xb3, 0x45, 0x76, 0x31, 0x4f, 0x16, 0x59, 0xe8, 0xcd, 0xf6,
	0x10, 0x26, 0x76, 0xe9, 0x33, 0x2d, 0x04, 0x3f, 0x80, 0xaf, 0x2c, 0xe0, 0xbd, 0x45, 0xb3, 0x87,
	0xa3, 0xa3, 0x07, 0x27, 0x4d, 0x1d, 0x1f, 0xe0, 0x09, 0xf4, 0xb4, 0x50, 0xc4, 0xae, 0xdc, 0x25,
	0x3c, 0x7a, 0xf1, 0xcf, 0x99, 0x1a, 0xba, 0xee, 0xb5, 0x3f, 0xd8, 0xc9, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x05, 0xbf, 0x35, 0x88, 0x73, 0x03, 0x00, 0x00,
}
